### ISSUE TITLE
Video Tab on Channel Page doesn't work properly.

### ISSUE THREAD

**Issue by igoutta** [calumks/youtube-audio-mode#1]
The video tab on a channel doesn't load old videos when I have your script activaded (more info, with option turned off for audio),  and the left panel doesn't show any block. Here the problem in picture.
![ed869d87-e170-4129-a759-8a03635252d8](https://user-images.githubusercontent.com/10776042/45078847-a3983d80-b0b6-11e8-9d12-702a1b31fdfc.png)

**Comment by teaqu** [comment]
This is because of YouTube's new layout. https://greasyfork.org/en/scripts/32906-get-me-old-youtube will revert to the old layout however I don't recommend you use this add-on if you're looking for performance improvements.

**Comment by teaqu** [comment]
So from what I can see, browsers are already pretty good at running video in the background (especially browsers like Edge) so I'm not not sure there will be much benefit only running audio or at least I can't see much myself. I don't want to fix this issue on YouTube's new layout as it requires a pretty extensive redesign to this script and the new layout is so slow that one might as well use the old layout until Google either fix or remove it. I hope that makes more sense!

**Comment by teaqu** [comment]
Had a change of heart. Could see some performance benefits again. Latest commit should fix this issue.
